Django_level_four/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.urls import path, include

#TEMPLATE TAGGING

app_name = 'basic_app'

urlpatterns = [

    path('relative/', views.relative,name='relative'),
    path('other/', views.other, name='other'),
    path('index/', views.index, name='index'),

]

Django_level_four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'))
]

Django_level_four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Django_level_four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request,'basic_app/index.html', context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

Django_level_four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:other'%}">Other</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>

  </body>
</html>

Django_level_four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <h1>{{ text|cut:'hello' }}</h1>
    <h2>{{ number|add:"99" }}</h2>
  {% endblock %}

Django_level_four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of template inheritance!</h2>

  {% endblock %}

Django_level_four/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'basic_app:index' %}">LINK TO INDEX</a>
  </body>
</html>